### ISSUE TITLE
USB driver not working on Windows 10

### ISSUE THREAD

**Issue by ghost** [map220v/MiPad5-Drivers#10]
Good afternoon. Tried installing windows 10 on our tablet, was surprised to find that it runs much faster than 11 windows, but there are a couple of drawbacks. Apart from the camera not working, which I have no complaints about, USB doesn't work. To be more precise, it works for charging, but devices connected via it are not visible. It has an error sign in the task manager. There is also one unrecognized device and a couple of uninstalled TPM drivers that I don't really care about. Is it possible to do something with USB and that unrecognized device?
![5233632807018945151_121](https://github.com/map220v/MiPad5-Drivers/assets/20730653/3755e468-0e6e-43a8-9ec4-8b6a1811530b)
![Annotation 2024-04-08 224143](https://github.com/map220v/MiPad5-Drivers/assets/20730653/be560c35-426a-487d-9eb7-2b6d19dca284)
![Annotation 2024-04-08 224158](https://github.com/map220v/MiPad5-Drivers/assets/20730653/a1143dfb-bb3e-41b5-903b-609195a0649f)

**Comment by ghost** [comment]
Double-checked on windows 11, doesn't work either

**Comment by map220v** [comment]
It seems that you are using DualRole USB mode, you need to force USB into Host Mode for connected USB devices to be detected, run this in admin cmd ```reg add "\HKLM\SYSTEM\CurrentControlSet\Enum\ACPI\QCOM0597\0\Device Parameters" /v RoleSwitchMode /t RED_DWORD /d 1``` and reboot device.

**Comment by ghost** [comment]
> It seems that you are using DualRole USB mode, you need to force USB into Host Mode for connected USB devices to be detected, run this in admin cmd `reg add "\HKLM\SYSTEM\CurrentControlSet\Enum\ACPI\QCOM0597\0\Device Parameters" /v RoleSwitchMode /t RED_DWORD /d 1` and reboot device.

It worked. I'll correct your command a little bit, there is a mistake in it, the correct one looks like this
reg add "HKLM\SYSTEM\CurrentControlSet\Enum\ACPI\QCOM0597\0\Device Parameters" /v RoleSwitchMode /t REG_DWORD /d 1

USB works, but there is still an unauthorized device in the dispatcher. 
ACPI\VEN_FSA&DEV_4480&SUBSYS_MTP08150

![Screenshot 2024-04-12 005813](https://github.com/map220v/MiPad5-Drivers/assets/20730653/f2655752-eae9-484b-bc05-1a9aa56348ca)

**Comment by map220v** [comment]
> USB works, but there is still an unauthorized device in the dispatcher.
ACPI\VEN_FSA&DEV_4480&SUBSYS_MTP08150

FSA4480 is currently removed, since it crashes on some Pad 5 revisions, and audio devices without DAC seem to work without it.
