### ISSUE TITLE
fsa4480.sys error on start

### ISSUE THREAD

**Issue by AnotherJack260** [map220v/MiPad5-Drivers#2]
System Thread Exception Not Handled error on startup

**Comment by map220v** [comment]
From https://t.me/nabuwoa

> If you get fsa4480.sys blue screen, please do this.
> 
> 1. Remove USB drivers from Driver pack - delete components\QC8150\Device\DEVICE.SOC_QC8150.NABU\Drivers\USB folder.
> 2. Reinstall drivers via driverupdater.exe - [How to update drivers](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/update-en.md) 
> 3. After setup reinstall drivers with USB drivers.
