### ISSUE TITLE
Multi touch screen interference

### ISSUE THREAD

**Issue by netsflex** [map220v/MiPad5-Drivers#4]
When touching different zones of the screen quickly, the operation will be seen as a single touch point moving, causing the mistouch. Due to this problem, it's hard to use the zoom gesture.

**Comment by Soneoylys** [comment]
Confirmed with latest commit, but doubt this is a UEFI firmware bug instead of drivers, as well as PD charging.

**Comment by map220v** [comment]
Fixed in https://github.com/map220v/MiPad5-Drivers/commit/ff34441706ac1b00b8ec6fab9b6533309f5d16f2
