### ISSUE TITLE
[Question] Light sensor driver

### ISSUE THREAD

**Issue by Soneoylys** [map220v/MiPad5-Drivers#6]
Recently I found some mismatch between documents in different languages at [this repo]( https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5), which claimed the light sensor works in Italian, Turkish and Chinese, but not others.

So I dig down to figure which side is correct, and I found [this discussion](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/issues/61), It points out "it used to work when map220v used the surface sensor drivers but now he used the generic qcom ones".

Which I believe refers to this two Commits:
- [Use sensors driver from Surface Duo to fix Light Sensor](https://github.com/map220v/MiPad5-Drivers/commit/1e15e6291b4218aaabe810d4030be1d9b45173f8)
- [Use latest Qualcomm's Sensors driver](https://github.com/map220v/MiPad5-Drivers/commit/957347d03c1aaa11c806112a8b840d85612e9210)

Please correct me if I'm wrong but is there a reason for using the QCOM version of sensor driver instead of Surface Duo one, or just a mistake for replace the driver?

**Comment by map220v** [comment]
New versions of Surface Duo sensor driver have many changes that won't work properly on other devices.
Old version of Surface Duo sensor driver won't work with latest drivers because of changes in FASTRPC.
