### ISSUE TITLE
[QUESTION] - Fastest core is locked to 800Mhz

### ISSUE THREAD

**Issue by xXPOLYGONXx** [map220v/MiPad5-Drivers#8]
Hello map220v,

I observed that the fastest core of my MiPad 5 is only running at 800Mhz which should be to 2960Mhz. I attached screenshots of CPU-Z and TaskManager, which show that one core clocking really slow, even though I am running Cinebench to put load on all cores.
Since the other cores show the right frequency and I can see that they are dynamically changing, I think that the 800Mhz are not a reading error of the software. Furthermore CPU-Z shows that the one fast core should have a frequency of 2420Mhz like the other 3 fast cores which suggests that there is at least something wrong.

Is the frequency a value which is controlled by the drivers in this project? I didnt find any obvious code which is called cpu-freq or similar. There is also a similar report in the [Installation manual by erdilS](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/issues/119).

Best regards

![taskmanager](https://github.com/map220v/MiPad5-Drivers/assets/4340703/8cf4fbd9-5615-4c76-af0a-2dd056504f83)
![CpuZ](https://github.com/map220v/MiPad5-Drivers/assets/4340703/347a5e41-79da-4080-937e-0e409d1570ab)

**Comment by map220v** [comment]
PEP driver should set max frequency for cores, but it doesn't support more than 2 clusters, so prime core is stuck at low frequency.
In last UEFI(12/02/2024 V3) Prime core was forced to max frequency using ClockDxe, so this issue should be fixed if you use latest UEFI.
https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/releases/download/UEFI/uefi-v3.img
